"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Fraction = exports.multiply = exports.divide = exports.subtract = exports.sum = void 0;
const operations_1 = require("./lib/operations");
Object.defineProperty(exports, "sum", { enumerable: true, get: function () { return operations_1.sum; } });
Object.defineProperty(exports, "subtract", { enumerable: true, get: function () { return operations_1.subtract; } });
Object.defineProperty(exports, "divide", { enumerable: true, get: function () { return operations_1.divide; } });
Object.defineProperty(exports, "multiply", { enumerable: true, get: function () { return operations_1.multiply; } });
const fractions_1 = require("./lib/fractions");
Object.defineProperty(exports, "Fraction", { enumerable: true, get: function () { return fractions_1.Fraction; } });
